import type { TemplateDefinition } from "../schema";

/** Birthday — "Paper party" (docs/design/theme-worlds/birthday.md). */
export const birthday = {
  id: "birthday",
  version: 1,
  status: "published",
  origin: "studio",
  category: "birthday",
  occasions: ["birthday", "milestone-birthday"],
  moods: ["playful", "joyful", "warm"],
  tags: ["cut-paper", "poster", "colour"],
  contentTypes: ["text", "photo", "video", "audio"],
  pricing: "included",
  renderer: 1,
  spec: {
    composition: "paper-party",
    finale: "paper-encore",
    type: "soft-poster",
    dark: false,
    palette: {
      ground: "#d85a31",
      groundDeep: "#bd4a26",
      card: "#fcf2e3",
      ink: "#2b1327",
      inkSoft: "#6b3a4f",
      onGround: "#2b1327",
      accent: "#edb046",
      accent2: "#eaa4ac",
      accent3: "#1e5f5b",
      light: "#fff4e4",
      rule: "rgb(43 19 39 / 0.2)",
      shadow: "84 26 10",
    },
    room: { base: "#f6e4c8", glow: "rgb(255 246 230 / 0.7)", texture: "paper-tooth", textureSize: 256, dark: false },
    greeting: {
      entrance: "balloons",
      particle: "confetti",
      palette: {
        background: "linear-gradient(180deg, #fff6ea 0%, #ffe6d2 100%)",
        base: "#fff1e2",
        text: "#3b1e14",
        textMuted: "#7b5344",
        accent: "#c63f26",
        onAccent: "#ffffff",
        card: "rgb(255 255 255 / 0.72)",
        line: "rgb(59 30 20 / 0.12)",
        envelope: "#ffffff",
        envelopeFlap: "#fdebdc",
        envelopeInk: "#7b5344",
        seal: "#df4f35",
        sealInk: "#fff4ea",
        paper: "#fffdf8",
        paperInk: "#3b1e14",
        paperInkSoft: "#7b5344",
        liner: "repeating-linear-gradient(45deg, #df4f35 0 6px, #fff4e8 6px 12px)",
        particleColors: ["#df4f35", "#f4a52a", "#3a9d8f", "#6c5fd3", "#f07fa8"],
        dark: false,
      },
    },
    audio: "none",
  },
} as const satisfies TemplateDefinition;
