import type { TemplateDefinition } from "../schema";

/** Celebration — "Signal" (docs/design/theme-worlds/celebration.md). */
export const celebration = {
  id: "celebration",
  version: 1,
  status: "published",
  origin: "studio",
  category: "celebration",
  occasions: ["congratulations", "graduation", "promotion", "achievement"],
  moods: ["energetic", "proud", "joyful"],
  tags: ["night-sky", "light-burst", "condensed-type"],
  contentTypes: ["text", "photo", "video", "audio"],
  pricing: "included",
  renderer: 1,
  spec: {
    composition: "signal",
    finale: "afterglow",
    type: "condensed-signal",
    dark: true,
    palette: {
      ground: "#1b2149",
      groundDeep: "#0c1030",
      card: "#f6f0e3",
      ink: "#161a38",
      inkSoft: "#4b5076",
      onGround: "#f8f2e6",
      accent: "#f0aa3c",
      accent2: "#8f9ddd",
      accent3: "#f8f2e6",
      light: "#f0aa3c",
      rule: "rgb(248 242 230 / 0.25)",
      shadow: "4 6 22",
    },
    room: { base: "#0b0e27", glow: "rgb(70 82 150 / 0.32)", texture: "night-sky", blend: "screen", dark: true },
    greeting: {
      entrance: "balloons",
      particle: "stars",
      palette: {
        background: "radial-gradient(120% 80% at 50% 0%, #34387a 0%, #1a1c4a 50%, #0c0d26 100%)",
        base: "#0e0f2a",
        text: "#f3f2ff",
        textMuted: "rgb(243 242 255 / 0.72)",
        accent: "#ffd479",
        onAccent: "#1c1a3d",
        card: "rgb(255 255 255 / 0.07)",
        line: "rgb(255 255 255 / 0.15)",
        envelope: "#f8f4ea",
        envelopeFlap: "#ede6d6",
        envelopeInk: "#34387a",
        seal: "#3d4296",
        sealInk: "#ffd479",
        paper: "#fbf8f1",
        paperInk: "#1f2150",
        paperInkSoft: "#555a8c",
        liner: "radial-gradient(#ffd479 0 1.2px, transparent 1.8px) 0 0 / 12px 12px, radial-gradient(#ffffff 0 0.8px, transparent 1.3px) 6px 6px / 12px 12px, #2b2f6b",
        particleColors: ["#ffd479", "#ffffff", "#b9bcff"],
        dark: true,
      },
    },
    audio: "none",
  },
} as const satisfies TemplateDefinition;
