import type { TemplateDefinition } from "../schema";

/** Minimal — "Just the words" (docs/design/theme-worlds/minimal.md). The default for a new greeting. */
export const minimal = {
  id: "minimal",
  version: 1,
  status: "published",
  origin: "studio",
  category: "essentials",
  occasions: ["just-because", "thank-you", "any"],
  moods: ["quiet", "calm", "restrained"],
  tags: ["typography", "grid", "white-space"],
  contentTypes: ["text", "photo", "video", "audio"],
  pricing: "included",
  renderer: 1,
  spec: {
    composition: "just-words",
    finale: "full-stop",
    type: "quiet-sans",
    dark: false,
    palette: {
      ground: "#ebe7e0",
      groundDeep: "#e0dbd2",
      card: "#fdfbf7",
      ink: "#1a1917",
      inkSoft: "#6a655e",
      onGround: "#1a1917",
      accent: "#c0472c",
      accent2: "#1a1917",
      accent3: "#fdfbf7",
      light: "#ffffff",
      rule: "rgb(26 25 23 / 0.14)",
      shadow: "40 34 28",
    },
    room: { base: "#f2eee7", glow: "rgb(255 255 255 / 0.65)", texture: "paper-tooth", textureSize: 256, dark: false },
    greeting: {
      entrance: "fade",
      particle: "none",
      palette: {
        background: "radial-gradient(120% 90% at 50% 0%, #f3f0ea 0%, #e7e2da 100%)",
        base: "#ebe7e0",
        text: "#161514",
        textMuted: "#5f5a55",
        accent: "#161514",
        onAccent: "#f6f4f0",
        card: "rgb(255 255 255 / 0.85)",
        line: "rgb(22 21 20 / 0.1)",
        envelope: "#ffffff",
        envelopeFlap: "#f1eee8",
        envelopeInk: "#5f5a55",
        seal: "#161514",
        sealInk: "#f6f4f0",
        paper: "#ffffff",
        paperInk: "#161514",
        paperInkSoft: "#6b6660",
        edge: "rgb(84 70 52 / 0.12)",
        liner: "repeating-linear-gradient(0deg, #e9e5de 0 1px, #f4f1ec 1px 9px)",
        particleColors: [],
        dark: false,
      },
    },
    audio: "none",
  },
} as const satisfies TemplateDefinition;
