import type { TemplateDefinition } from "../schema";

/** Romantic — "Quiet light" (docs/design/theme-worlds/romantic.md). */
export const romantic = {
  id: "romantic",
  version: 1,
  status: "published",
  origin: "studio",
  category: "love",
  occasions: ["anniversary", "love-note", "valentines-day", "just-because"],
  moods: ["intimate", "warm", "quiet"],
  tags: ["letter", "window-light", "botanical", "linen"],
  contentTypes: ["text", "photo", "video", "audio"],
  pricing: "included",
  renderer: 1,
  spec: {
    composition: "quiet-light",
    finale: "evening-falls",
    type: "letter-italic",
    dark: true,
    palette: {
      ground: "#93665e",
      groundDeep: "#4d2a2b",
      card: "#f7eee4",
      ink: "#4a1f26",
      inkSoft: "#85605b",
      onGround: "#fbf0e6",
      accent: "#e6c3b4",
      accent2: "#bf8c84",
      accent3: "#f7eee4",
      light: "#ffe3c9",
      rule: "rgb(74 31 38 / 0.22)",
      shadow: "58 22 24",
    },
    room: { base: "#3b2224", glow: "rgb(150 96 88 / 0.38)", texture: "linen", textureSize: 192, dark: true },
    greeting: {
      entrance: "envelope",
      particle: "petals",
      palette: {
        background: "radial-gradient(120% 80% at 50% 0%, #7a3244 0%, #4a1827 45%, #2a0e17 100%)",
        base: "#2a0e17",
        text: "#fcefef",
        textMuted: "rgb(252 239 239 / 0.74)",
        accent: "#f3c1bb",
        onAccent: "#3a1320",
        card: "rgb(255 255 255 / 0.08)",
        line: "rgb(255 255 255 / 0.16)",
        envelope: "#f6e7df",
        envelopeFlap: "#ecd5ca",
        envelopeInk: "#5a2332",
        seal: "#9e2f47",
        sealInk: "#fbe3e1",
        paper: "#fbf3ee",
        paperInk: "#4a1827",
        paperInkSoft: "#8a5a63",
        liner: "repeating-linear-gradient(135deg, #9e2f47 0 7px, #b54a60 7px 14px)",
        particleColors: ["#f6b8bd", "#f9d3d0", "#e98c98"],
        dark: true,
      },
    },
    audio: "none",
  },
} as const satisfies TemplateDefinition;
