import type { TemplateDefinition } from "../schema";

/** Wedding — "Vellum & emboss" (docs/design/theme-worlds/wedding.md). */
export const wedding = {
  id: "wedding",
  version: 1,
  status: "published",
  origin: "studio",
  category: "wedding",
  occasions: ["wedding", "engagement", "anniversary"],
  moods: ["ceremonial", "timeless", "calm"],
  tags: ["vellum", "letterpress", "botanical", "olive"],
  contentTypes: ["text", "photo", "video", "audio"],
  pricing: "included",
  renderer: 1,
  spec: {
    composition: "vellum",
    finale: "vellum-close",
    type: "ceremonial-garamond",
    dark: false,
    palette: {
      ground: "#b4b6a4",
      groundDeep: "#9c9f8b",
      card: "#fbf9f3",
      ink: "#2b332c",
      inkSoft: "#5d695e",
      onGround: "#2b332c",
      accent: "#76845f",
      accent2: "#c8cdbd",
      accent3: "#fbf9f3",
      light: "#ffffff",
      rule: "rgb(43 51 44 / 0.3)",
      shadow: "44 52 40",
    },
    room: { base: "#d2d4c6", glow: "rgb(255 255 250 / 0.55)", texture: "paper-tooth", textureSize: 256, dark: false },
    greeting: {
      entrance: "envelope",
      particle: "petals",
      palette: {
        background: "linear-gradient(180deg, #f7f4ec 0%, #e8ede2 100%)",
        base: "#f1f1e8",
        text: "#253029",
        textMuted: "#56635a",
        accent: "#56704f",
        onAccent: "#ffffff",
        card: "rgb(255 255 255 / 0.72)",
        line: "rgb(37 48 41 / 0.12)",
        envelope: "#fffdf8",
        envelopeFlap: "#f0ece1",
        envelopeInk: "#5b675e",
        seal: "#6f8b69",
        sealInk: "#f7f4ec",
        paper: "#fffdf7",
        paperInk: "#253029",
        paperInkSoft: "#5b675e",
        liner:
          "repeating-linear-gradient(45deg, rgb(111 139 105 / 0.55) 0 1px, transparent 1px 9px), repeating-linear-gradient(-45deg, rgb(111 139 105 / 0.55) 0 1px, transparent 1px 9px), #e6ecdf",
        particleColors: ["#ffffff", "#f3efe4", "#dfe8d8"],
        dark: false,
      },
    },
    audio: "none",
  },
} as const satisfies TemplateDefinition;
